services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=leetify
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: